[build]
  base = "F_StudyHub"
  command = "flutter build web --dart-define=API_URL=https://studyhub-api.onrender.com --dart-define=SOCKET_URL=https://studyhub-api.onrender.com"
  publish = "build/web"
